### ISSUE TITLE
Gnome 45 Support?

### ISSUE THREAD

**Issue by nater1983** [danchris/eortologio-gnome-shell-extension#4]
Is there any chance you will port this to the new ESM for Gnome 45???

**Comment by danchris** [comment]
Right now, I don't see any reason to go ahead with the port to the new ESM since Gnome 45 is still in beta.

It seems that ESM will bring breaking changes.  However, this project is quite simple and I don't see anything that makes it difficult for us. If you feel ready feel free to give it a try yourself otherwise I'll look into it sometime next month.

**Comment by nater1983** [comment]
https://github.com/danchris/eortologio-gnome-shell-extension/pull/5
This is a start of the 45 ESM Port

**Comment by nater1983** [comment]
![image](https://github.com/danchris/eortologio-gnome-shell-extension/assets/46272571/ba3a76ff-cc6e-4edb-a92b-33276cc6cea9)

**Comment by danchris** [comment]
Resolved #5
